name: Generate CS-PHOC Darwin Core Archive (DwCA) files from standardized CSV files

on:
  push:
    branches: [main]
    paths:
      - R/data_to_dwca.R
      - data/manuscript
  pull_request:
    branches: [main]
    paths:
      - R/data_to_dwca.R
      - data/manuscript/**

jobs:
  generate-data:
    runs-on: windows-latest
    # runs-on: ubuntu-latest #errors out when installing 'units' package
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'
      - uses: r-lib/actions/setup-renv@v2

      - name: Generate data # Run the script
        run: source("R/data_to_dwca.R")
        shell: Rscript {0}
      
      - name: Commit files # Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || (git commit -m "update data" && git push)
